### ISSUE TITLE
Build files missing?

### ISSUE THREAD

**Issue by kirjai** [sapegin/stack-styled#16]
Just tried installing this library, but unfortunately it seems that the build files are missing from the latest version?

After running `yarn add stack-styled`, what I get in `node_modules` is:

<img width="279" alt="Screenshot 2020-09-04 at 14 46 59" src="https://user-images.githubusercontent.com/9858620/92246393-98529500-eebd-11ea-9db3-deb4a6d1bfd5.png">

This manifests itself in an error, when trying to build the project that imports `stack-styled` with the following error:
```
Module not found: Error: Can't resolve 'stack-styled'
```

**Comment by sapegin** [comment]
Hm, something is wrong with the configuration:

```
❯ npm run build

> stack-styled@3.0.0 build /Users/artim.sapegin/_/stack-styled
> npm run build:esm && npm run build:cjs && npm run build:emotion && npm run build:types


> stack-styled@3.0.0 build:esm /Users/artim.sapegin/_/stack-styled
> babel --delete-dir-on-start --ignore '**/*.spec.js' -d esm/ src/

Successfully compiled 0 files with Babel.

> stack-styled@3.0.0 build:cjs /Users/artim.sapegin/_/stack-styled
> babel --delete-dir-on-start --ignore '**/*.spec.js' --env-name cjs -d lib/ src/

Successfully compiled 0 files with Babel.

> stack-styled@3.0.0 build:emotion /Users/artim.sapegin/_/stack-styled
> babel --delete-dir-on-start --ignore '**/*.spec.js' --env-name emotion -d emotion/ src/

Successfully compiled 0 files with Babel.

> stack-styled@3.0.0 build:types /Users/artim.sapegin/_/stack-styled
> tsc --emitDeclarationOnly
```

**Comment by sapegin** [comment]
Seems to work now:

![image](https://user-images.githubusercontent.com/70067/92254483-40be2480-eed1-11ea-83bb-8f3a0276d286.png)

**Comment by kirjai** [comment]
sweet, thanks for a quick resolution!
