### ISSUE TITLE
Choose different name for minWidth prop

### ISSUE THREAD

**Issue by sapegin** [sapegin/stack-styled#2]
To avoid a conflict with `minWidth` (`min-width` CSS property) [in styled-system](https://styled-system.com/table#layout).

Looks like it's also generating CSS for `min-width`:

```css
  box-sizing: border-box;
  min-width: small;
  display: grid;
  grid-template-columns: repeat(auto-fit,minmax(32rem,1fr));
  grid-gap: 2px;
```

`minColumnWidth` looks like a good alternative. Also more clear what it does.

- [ ] Rename `minWidth` to `minColumnWidth`
- [ ] Update docs

**Comment by okonet** [comment]
Or just `itemWidth`?

**Comment by sapegin** [comment]
I think `column` better fit into CSS Grid because they call them _columns_. And it's the minimum width of a column, so I think `minColumnWidth` is the most precise and clear name.

**Comment by okonet** [comment]
Agreed!
